let num1 = parseInt(prompt('Vilket nummer?'));
let num2 = parseInt(prompt('Vilket nummer?'));
let plus = num1 + num2;
console.log(plus);
let minus = num1 - num2;
console.log(minus);
let gånger = num1 * num2;
console.log(gånger);
let delat = num1 / num2;
console.log(delat);
alert('Svaret blir ' + delat);
console.log('Svaret blir ' + delat);